version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
#    networks:
#      - main_net
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5666:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=booking
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  sleephub:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/booking
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=password
    ports:
      - '9990:9990'
    depends_on:
      - db
      - minio
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  minio_storage: {}
  db:
    driver: local